PackageName: "NLPModelsModifiers"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "e01155f1-5c6f-4375-a9d8-616dd036575f"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "7bcc7d0a2905be7ca9d1dd6519e8df59ae89605c"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
AddCirrusCI: true
